update_wifi_network:
  fields:
    ssid:
      required: true
      selector:
        text: {}
    latitude:
      required: true
      selector:
        number:
          min: -90
          max: 90
          step: "any"
          mode: box
    longitude:
      required: true
      selector:
        number:
          min: -180
          max: 180
          step: "any"
          mode: box
