update_wifi_network:
  fields:
    ssid:
      required: true
      example: "MyNetwork"
      selector:
        text:
    latitude:
      required: true
      example: 37.7749
      selector:
        number:
          min: -90
          max: 90
          step: 0.000001
          mode: box
    longitude:
      required: true
      example: -122.4194
      selector:
        number:
          min: -180
          max: 180
          step: 0.000001
          mode: box
